version: '3'
services:
    webapp:
        image: tomcat
        ports:
            - "8080:8080"
        volumes:
            - .BankeeBackServices/target/BankeeBackServices-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
            - .BankeeBackServices/target/BankeeBackServices-1.0-SNAPSHOT:/usr/local/tomcat/webapps/ROOT
    postgres:
        image: postgres:9.4
        ports:
            - "5432:5432"
        volumes:
            - ./BankeeBackDataBase/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    