version: '3'
services:
    webapp:
        image: tomcat
        ports:
            - "8080:8080"
        links:
          - postgres
        volumes:
            - ./BankeeBackServices/target/BankeeBack.war:/usr/local/tomcat/webapps/ROOT.war
            - ./BankeeBackServices/target/BankeeBack:/usr/local/tomcat/webapps/ROOT
    postgres:
        image: postgres:9.4
        ports:
            - "5432:5432"
        volumes:
            - ./BankeeBackDataBase/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    